package com.mobilex.hub;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class color {
        public static final int r_xkvfeocmucfh = 0x7f010000;
        public static final int r_czctnarzjwum = 0x7f010001;
    }

    public static final class drawable {
        public static final int r_ixvcocxtvlvl = 0x7f020000;
    }

    public static final class mipmap {
        public static final int r_juhuioeuraxt = 0x7f030000;
        public static final int r_xwsqgpdgcejj = 0x7f030001;
    }

    public static final class string {
        public static final int r_irfwtwuogokq = 0x7f040000;
        public static final int r_tvmsilpptnmq = 0x7f040001;
        public static final int r_equhyvgkapeo = 0x7f040002;
        public static final int r_twlufzedqmge = 0x7f040003;
        public static final int r_joyatvqsdlnv = 0x7f040004;
        public static final int r_izevtramdcfc = 0x7f040005;
        public static final int r_cldwwsurxmoq = 0x7f040006;
        public static final int r_ahuzoqtmbcgr = 0x7f040007;
        public static final int r_vvpjkngpichj = 0x7f040008;
        public static final int r_xpzecckuavgj = 0x7f040009;
        public static final int r_nqvckazsvssd = 0x7f04000a;
        public static final int r_lppvwzzaxrcs = 0x7f04000b;
        public static final int r_szcsvtkymmug = 0x7f04000c;
        public static final int r_mgvkwvnrpefi = 0x7f04000d;
        public static final int r_duyjoeumywrq = 0x7f04000e;
        public static final int r_bpdfsrwaxanb = 0x7f04000f;
        public static final int r_xyywuawazkww = 0x7f040010;
        public static final int r_hxmyguazvryt = 0x7f040011;
        public static final int r_luptnjvppwyo = 0x7f040012;
        public static final int r_djlzrpjwezol = 0x7f040013;
        public static final int r_czvwntnnzvpp = 0x7f040014;
        public static final int r_rphnahntfvrn = 0x7f040015;
        public static final int r_gvkhfhiznskj = 0x7f040016;
        public static final int r_ridasmywaoih = 0x7f040017;
        public static final int r_dptuyoijltzx = 0x7f040018;
        public static final int r_zizqzicaqgmi = 0x7f040019;
        public static final int r_lbwsyfoiddrd = 0x7f04001a;
        public static final int r_ekjrczwhlmfh = 0x7f04001b;
        public static final int r_jkreaajejadb = 0x7f04001c;
        public static final int r_uhmtrfhguaip = 0x7f04001d;
        public static final int r_wmnokysvnpeo = 0x7f04001e;
        public static final int r_gqkesdynqeik = 0x7f04001f;
        public static final int r_fqnvrvbryvnk = 0x7f040020;
        public static final int r_obpcgdqgnyac = 0x7f040021;
        public static final int r_ddickkroladd = 0x7f040022;
        public static final int r_hhoxozjktbbr = 0x7f040023;
        public static final int r_qaummrrmfrxa = 0x7f040024;
        public static final int r_hcwoxaktlrag = 0x7f040025;
        public static final int r_paqxknrwpazj = 0x7f040026;
        public static final int r_ptiynvlxfehb = 0x7f040027;
        public static final int r_nqyjpxqmxqdb = 0x7f040028;
        public static final int r_kzujskpqzhsk = 0x7f040029;
        public static final int r_ntnxzsoobwtp = 0x7f04002a;
        public static final int r_ccqwyjtskbmb = 0x7f04002b;
        public static final int r_heymfoeolgho = 0x7f04002c;
        public static final int r_skznjpplpqmh = 0x7f04002d;
        public static final int r_yvfuciwweolj = 0x7f04002e;
        public static final int r_bekowspcsvvu = 0x7f04002f;
        public static final int r_hpgxhvogxmjf = 0x7f040030;
        public static final int r_exuwxpihltee = 0x7f040031;
        public static final int r_bcuylsbfnmur = 0x7f040032;
        public static final int r_legzeuffcmmp = 0x7f040033;
        public static final int r_bcxewtbzyryn = 0x7f040034;
        public static final int r_ggsthmonugtc = 0x7f040035;
        public static final int r_btfmlsgalkkz = 0x7f040036;
        public static final int r_rekjttorvnpd = 0x7f040037;
        public static final int r_nrmgfsmkxruk = 0x7f040038;
        public static final int r_dsynrxcalpms = 0x7f040039;
        public static final int r_ibejzixzscfg = 0x7f04003a;
        public static final int r_kdnpqdulooai = 0x7f04003b;
        public static final int r_wpmtprechbra = 0x7f04003c;
        public static final int r_alnsflmdtixr = 0x7f04003d;
        public static final int r_uusypwmrfpwn = 0x7f04003e;
        public static final int r_anlhwcmbjing = 0x7f04003f;
        public static final int r_fuvcsbzcqdgx = 0x7f040040;
        public static final int r_cyuakitqvkgc = 0x7f040041;
    }

    public static final class style {
        public static final int r_tcwduzvruxkl = 0x7f050000;
    }

    public static final class xml {
        public static final int r_eqeufsvqwqov = 0x7f060000;
    }
}
